### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by grmtns** [grmtns/zadanie4#1]
Проблема с файлом textfile.txt

**Comment by diskdiskov** [comment]
Здесь всё хорошо!

**Comment by grmtns** [comment]
Вы уверены? Я предлагаю добавить ещё пару важных строк!

**Comment by grmtns** [comment]
Вы уверены? Я предлагаю добавить ещё пару важных строк!

**Comment by grmtns** [comment]
Спасибо всем за участие!
